{% set name = "unbaffeld" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/UNBAFFELD-{{ version }}.tar.gz
  sha256: fce9ba4e328d08161030da3d9aea5ffb45d262672fb39249ea2fd2df3427e42b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - inference-tools >=0.12.0
    - numpy >=1.8
    - scipy >=1.6.3
    - h5py
    - matplotlib >=3.4.2

test:
  imports:
    - unbaffeld
  requires:
    - pip
  commands:
    - pip check


about:
  home: "https://gitlab.com/efit-ai/unbaffeld"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "UNBAFFELD: UNified Bayesian Analysis Framework for Fusion ExperimentaL Data"
  doc_url: 
  dev_url: http://www.gitlab.com/efit-ai/unbaffeld

extra:
  recipe-maintainers:
    - JarrodLeddy
